[build]
  command = "npm install sharp --ignore-engines && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

  [functions]
  external_node_modules = ["sharp"]
  included_files = ["node_modules/sharp/**/*"]
